import numpy as np
from pathlib import Path
from typing import Protocol
from langchain_core.tools import tool
from langchain_core.runnables import Runnable
from langchain_core.messages import AIMessage
from langchain_core.language_models import LanguageModelInput

from dreamcraft.domain import Quest, Waypoint, Skill, Observation
from dreamcraft.app.models import LoadJSResult, LoadJSResults

class IQuestRepo(Protocol):
    def add(self, quest: Quest):
        ...
    def get_quest(self, quest_id: int) -> Quest:
        ...
    def get_waypoint(self, ref: Waypoint | int | str, quest: Quest = None) -> Waypoint:
        ...

class IWikiRepo(Protocol):
    def query(self, query_embedding, top_k=3) -> list[dict]:
        ...
    def grep_files(self, pattern: str, max_results: int = -1) -> list[dict]:
        ...
    def read_section(self, file_name: str, section_title: str) -> str:
        ...

class ISkillRepo(Protocol):
    def query(self, query_embedding, top_k=3) -> list[dict]:
        ...
    def add(self, skill: Skill, skill_embedding: np.ndarray):
        ...
    def get(self, ref: int | str) -> Skill:
        ...
    def load_js_skill(self, js_path: Path) -> LoadJSResult:
        ...
    def load_js_dir_skills(self, dir: Path) -> LoadJSResults:
        ...
    def update_private_skills(self, private_skills: list[Skill]):
        ...
    def update_all_dependencies(self):
        ...

class ILLMClient(Protocol):
    def embed(self, text: str) -> np.ndarray:
        ...
    def with_tools(self, tools: list[tool]) -> Runnable[LanguageModelInput, AIMessage]:
        ...

class IPromptRepo(Protocol):
    def load(self, name: str)-> str:
        ...
    def react(self, role: str, query: str, extra: str = "", enable_context_compression: bool = True) -> str:
        ...
    def get_task_prompt(self, task) -> str:
        ...

class IToolRepo(Protocol):
    def __getitem__(self, key: str) -> tool:
        ...
    @property
    def all_tools(self) -> dict[str, tool]:
        ...
    def get_tools(self, tools: list[str]) -> list[tool]:
        ...

class IMinecraftClient(Protocol):
    async def execute(self, code: str) -> dict:
        ...
    async def start(self, options: dict = {}) -> Observation:
        ...
    async def observe(self) -> Observation:
        ...
